version: '3'
services:

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./apps/cart/:/var/www/cart
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/site/:/etc/nginx/conf.d/
    networks:
      - app-network

  cart:
    build:
      context: apps/cart
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    command: php-fpm -R

    working_dir: /var/www/cart
    volumes:
      - ./apps/cart/:/var/www/cart
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  db:
    container_name: db
    image: mariadb
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_ROOT: test
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/var/lib/mysql/my.cnf
    ports:
      - 3306:3306
    networks:
      - app-network
  dbadmin:
    container_name: dbadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - app-network
    ports:
      - "81:80"
    environment:
      MYSQL_ROOT_PASSWORD: root

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
